
import React from 'react';
import { AnalysisResult, AnalysisType } from '../types';

interface Props {
  result: AnalysisResult;
  type: AnalysisType;
}

const AnalysisResultView: React.FC<Props> = ({ result, type }) => {
  if (!result) return null;

  return (
    <div className="mt-16 space-y-12 animate-in fade-in slide-in-from-bottom-10 duration-1000 pb-20">
      <div className="flex items-center gap-6 mb-4">
        <h2 className="text-4xl font-black uppercase tracking-tighter italic">Analysis <span className="text-violet-500">Report</span></h2>
        <div className="h-[2px] flex-grow bg-gradient-to-r from-violet-600/50 via-white/5 to-transparent"></div>
        <div className="hidden sm:block text-[9px] font-black text-slate-500 uppercase tracking-widest bg-white/5 px-4 py-2 rounded-full border border-white/5">
          Neural-Engine: Gemini-3.0-Flash
        </div>
      </div>

      {type === AnalysisType.IMAGE_GEN ? (
        <div className="glass p-4 rounded-[3rem] border border-white/10 overflow-hidden shadow-[0_0_50px_rgba(139,92,246,0.1)] relative group max-w-5xl mx-auto transition-transform hover:scale-[1.01]">
          {result.generatedImageUrl ? (
            <img src={result.generatedImageUrl} className="w-full rounded-[2.5rem] shadow-2xl" alt="AI Generated Asset" />
          ) : (
            <div className="w-full aspect-video bg-slate-900 rounded-[2.5rem] flex items-center justify-center">
              <span className="text-slate-600 font-black uppercase tracking-widest">Image Data Corrupted</span>
            </div>
          )}
          <div className="absolute top-10 left-10 flex items-center gap-3 px-5 py-2.5 bg-black/80 backdrop-blur-xl rounded-full text-[10px] font-black uppercase tracking-widest border border-white/10">
            <span className="w-2.5 h-2.5 bg-violet-500 rounded-full animate-pulse shadow-[0_0_12px_rgba(139,92,246,1)]"></span>
            Neural Asset Finalized
          </div>
          <button 
            onClick={() => {
              if (result.generatedImageUrl) {
                const link = document.createElement('a');
                link.href = result.generatedImageUrl;
                link.download = `content-iq-${Date.now()}.png`;
                link.click();
              }
            }}
            className="absolute bottom-10 right-10 bg-violet-600 hover:bg-violet-700 text-white p-5 rounded-3xl shadow-2xl transition-all active:scale-95 group/dl"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" className="group-hover/dl:translate-y-0.5 transition-transform">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>
            </svg>
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-8 space-y-8">
            {type === AnalysisType.YOUTUBE && result.thumbnailUrl && (
              <div className="glass rounded-[2.5rem] p-3 border border-white/10 overflow-hidden shadow-2xl relative">
                <img src={result.thumbnailUrl} className="w-full aspect-video object-cover rounded-[1.8rem] opacity-90" alt="Video Feed" />
                <div className="absolute top-8 left-8 px-4 py-1.5 bg-black/80 backdrop-blur-md rounded-full text-[10px] font-black uppercase tracking-widest border border-white/10">Video Buffer Feed</div>
              </div>
            )}

            <div className="glass p-12 rounded-[2.5rem] border border-white/10 relative overflow-hidden shadow-xl">
              <div className="flex items-center justify-between mb-8">
                <h3 className="text-2xl font-black flex items-center gap-4 uppercase tracking-tighter">
                  <span className="w-1.5 h-7 bg-violet-500 rounded-full shadow-[0_0_12px_rgba(139,92,246,0.4)]"></span>
                  {type === AnalysisType.PDF_REFINE ? 'Refined Output' : 'Core Synopsis'}
                </h3>
                {type === AnalysisType.PDF_REFINE && (
                  <button 
                    onClick={() => navigator.clipboard.writeText(result.summary)}
                    className="px-5 py-2.5 bg-violet-600/10 border border-violet-500/30 hover:bg-violet-600/20 text-violet-400 rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
                  >
                    Copy Output
                  </button>
                )}
              </div>
              <div className="text-slate-300 leading-relaxed text-lg font-medium tracking-tight whitespace-pre-wrap font-mono bg-black/10 p-6 rounded-2xl border border-white/5">
                {result.summary || "No summary data generated by engine."}
              </div>
            </div>
            
            {result.improvements && result.improvements.length > 0 && (
              <div className="glass p-12 rounded-[2.5rem] border border-white/10 shadow-xl">
                <h3 className="text-2xl font-black mb-8 flex items-center gap-4 uppercase tracking-tighter">
                  <span className="w-1.5 h-7 bg-emerald-500 rounded-full shadow-[0_0_12px_rgba(16,185,129,0.4)]"></span>
                  Optimizations
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {result.improvements.map((imp, i) => (
                    <div key={i} className="flex gap-4 p-5 bg-white/5 rounded-2xl border border-white/5 hover:bg-white/10 transition-colors group">
                      <span className="text-emerald-500 font-black group-hover:scale-110 transition-transform">✓</span>
                      <p className="text-slate-300 text-sm font-bold leading-tight">{imp}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="lg:col-span-4 space-y-8">
            <div className="grid grid-cols-2 gap-4">
              <ScoreBadge label="Logic" score={result.scores?.clarity ?? 0} color="cyan" />
              <ScoreBadge label="Impact" score={result.scores?.engagement ?? 0} color="emerald" />
              <ScoreBadge label="Layout" score={result.scores?.structure ?? 0} color="purple" />
              <ScoreBadge label="Neural IQ" score={result.scores?.overall ?? 0} color="violet" />
            </div>

            <div className="glass p-10 rounded-[2.5rem] border border-violet-500/10 bg-violet-600/5">
              <h4 className="text-[10px] font-black text-violet-400 uppercase tracking-widest mb-8 text-center">Neural Tips</h4>
              <div className="space-y-6">
                {Object.entries(result.tips || {}).map(([key, value]) => (
                  value && (
                    <div key={key} className="relative pl-5 border-l-2 border-violet-500/20">
                      <h5 className="text-[8px] font-black uppercase tracking-widest text-violet-500/60 mb-1">{key}</h5>
                      <p className="text-[11px] text-slate-300 font-medium leading-relaxed">{value}</p>
                    </div>
                  )
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const ScoreBadge = ({ label, score, color }: { label: string; score: number; color: string }) => {
  const colorMap: any = {
    violet: 'text-violet-500',
    cyan: 'text-cyan-500',
    emerald: 'text-emerald-500',
    purple: 'text-purple-500'
  };
  return (
    <div className="glass p-5 rounded-3xl border border-white/5 flex flex-col items-center justify-center text-center group transition-all hover:bg-white/10">
      <span className="text-[8px] font-black uppercase tracking-widest text-slate-500 mb-3">{label}</span>
      <div className={`text-2xl font-black ${colorMap[color]} mb-1`}>{score}</div>
      <div className="w-8 h-1 bg-white/10 rounded-full overflow-hidden">
        <div 
          className={`h-full ${color === 'violet' ? 'bg-violet-500' : color === 'cyan' ? 'bg-cyan-500' : color === 'emerald' ? 'bg-emerald-500' : 'bg-purple-500'}`} 
          style={{ width: `${score}%` }}
        ></div>
      </div>
    </div>
  );
};

export default AnalysisResultView;
